<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
	 <LangVersion>preview</LangVersion>
    <PackageIcon>AppIcon.ico</PackageIcon>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="Views\3dAxis.png" />
  </ItemGroup>
  <ItemGroup>
    <None Include="..\.editorconfig" Link=".editorconfig" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.135" />
    <PackageReference Include="ModelContextProtocol" Version="0.4.0-preview.3" />
    <PackageReference Include="ModelContextProtocol.AspNetCore" Version="0.4.0-preview.3" />
    <PackageReference Include="SkiaSharp.Views.WPF" Version="3.119.2-preview.1" />
    <PackageReference Include="StyleCop.Analyzers" Version="1.2.0-beta.556">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.10" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.10" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="9.0.10" />
	<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Biosero.Kinematics.Common\Biosero.Kinematics.Common.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="AppIcon.ico" />
    <Resource Include="Views\3dAxis.png" />
  </ItemGroup>
  <ItemGroup>
    <None Update="AppIcon.ico">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>
</Project>