# For more info on HTTP files go to https://aka.ms/vs/httpfile
@hostAddress = http://localhost:7276

GET {{hostAddress}}/coordinates

###

GET {{hostAddress}}/railposition

###

GET {{hostAddress}}/recordedpoints

###

GET {{hostAddress}}/stepprecision

###

POST {{hostAddress}}/move
Content-Type: application/json

{
  "x": "20",
  "y": "0",
  "z": "10",
  "rail": "0"
}

###

POST {{hostAddress}}/play
Content-Type: application/json

{
}

###

POST {{hostAddress}}/recordpoint
Content-Type: application/json

{
}
